const actionTypes = {
  SET_VOCABULARY: 'SET_VOCABULARY',
  DELETE_VOCABULARY: 'DELETE_VOCABULARY',
  CHANGE_NAME_VOCABULARY: 'CHANGE_NAME_VOCABULARY',
  SET_WORD: 'SET_WORD',
  DELETE_WORD: 'DELETE_WORD',
};

export default actionTypes;
