const actionTypes = {
  VOCABULARY_SET: 'VOCABULARY_SET',
  VOCABULARY_DELETE: 'VOCABULARY_DELETE',
  VOCABULARY_CHANGE_NAME: 'VOCABULARY_CHANGE_NAME',
  WORD_SET: 'WORD_SET',
  WORD_DELETE: 'WORD_DELETE',
  LANDSCAPE_ORIENTATION_SET: 'LANDSCAPE_ORIENTATION_SET',
};

export default actionTypes;
